### ISSUE TITLE
Support for GlobalCategoricalActionSpace when loading a model from a checkpoint

### ISSUE THREAD

**Issue by drchangliu** [entity-neural-network/enn-trainer#32]
When the following code is used to load a model from a checkpoint:
```
from enn_trainer import load_checkpoint, RogueNetAgent
from entity_gym.env import *
checkpoint = load_checkpoint('checkpoints/latest-step000000008192')
agent = RogueNetAgent(checkpoint.state.agent)
obs = Observation(
   features={
       "Cluster": [[5, 3], [17, 2], [19, 3], [22, -4]],
       "Tensor": [[2, 1, 2, 0], [22, 1, 2, 0]],
   },
   done=True,
   reward=0.0,
   actions={"move": GlobalCategoricalActionMask()},
)
action, predicted_return = agent.act(obs)
```

The following error was reported:
```
(games38) $ python load_checkpoint.py 
Traceback (most recent call last):
  File "load_checkpoint.py", line 14, in <module>
    action, predicted_return = agent.act(obs)
  File "/opt/conda/envs/games38/lib/python3.8/site-packages/enn_trainer/agent.py", line 61, in act
    vec_obs = batch_obs([obs], self.agent.obs_space, self.agent.action_space)
  File "/opt/conda/envs/games38/lib/python3.8/site-packages/entity_gym/env/vec_env.py", line 364, in batch_obs
    raise ValueError(
ValueError: Unsupported action space type: <class 'entity_gym.env.action.GlobalCategoricalActionSpace'>
```

Please add support for **GlobalCategoricalActionSpace** or suggest an alternative action space type to use. Thanks.

**Comment by cswinter** [comment]
Possibly this fixes it, haven't tested yet but might work if you want to try: https://github.com/entity-neural-network/entity-gym/pull/25

If not, could you upload your checkpoint file?

**Comment by drchangliu** [comment]
Yes, this fixed the issue.
